---
- name: Update Proxmox LXC Containers
  hosts: proxmox
  become: yes
  vars:
    # List the VMIDs of the containers you want to update
    lxc_container_ids:
      - 100
      - 101
      - 102

  tasks:
    - name: Update and Upgrade LXC Containers
      community.proxmox.proxmox_pct_remote:
        vmid: "{{ item }}"
        cmd: "apt-get update && apt-get dist-upgrade -y"
      loop: "{{ lxc_container_ids }}"
      register: update_results

    - name: Display Update Results
      debug:
        var: update_results.results[item].stdout
      loop: "{{ range(0, lxc_container_ids|length) | list }}"
